### ISSUE TITLE
Google's terms of service status

### ISSUE THREAD

**Issue by taseenb** [spite/PanomNom.js#4]
Hi @spite I'm doing some research for a project about Google's TOS and Street View images.

What's the difference between this project and the https://github.com/spite/GSVPano.js ? You said that you had to remove that one for enabling people to break Google's Terms of Service. Did you have any confirmation from Google that with PanomNom (which also allows to extrapolate and download images) it wasn't the case?

**Comment by spite** [comment]
The terms haven't changed AFAIK. This repo would face the same consequences as GSVPano. 

If you need to handle Street View tiles the official way, you have to contact a Google Maps Sales representative and ask for a license (which they will probably won't grant, or it will be astronomically expensive)

**Comment by taseenb** [comment]
Thanks!
